package com.sun.jna.platform.win32.office.outlook;
/*
 * Would really like this to have been a type-safe enum sort of class. However it has to be
 * just a set of public int constants so that it can be used in case statements.
 */

public final class ClassEnum {

	public final static int	olAccount	=	105	;  //	An Account object.
	public final static int	olAccountRuleCondition	=	135	;  //	An AccountRuleCondition object.
	public final static int	olAccounts	=	106	;  //	An Accounts object.
	public final static int	olAction	=	32	;  //	An Action object.
	public final static int	olActions	=	33	;  //	An Actions object.
	public final static int	olAddressEntries	=	21	;  //	An AddressEntries object.
	public final static int	olAddressEntry	=	8	;  //	An AddressEntry object.
	public final static int	olAddressList	=	7	;  //	An AddressList object.
	public final static int	olAddressLists	=	20	;  //	An AddressLists object.
	public final static int	olAddressRuleCondition	=	170	;  //	An AddressRuleCondition object.
	public final static int	olApplication	=	0	;  //	An Application object.
	public final static int	olAppointment	=	26	;  //	An AppointmentItem object.
	public final static int	olAssignToCategoryRuleAction	=	122	;  //	An AssignToCategoryRuleAction object.
	public final static int	olAttachment	=	5	;  //	An Attachment object.
	public final static int	olAttachments	=	18	;  //	An Attachments object.
	public final static int	olAttachmentSelection	=	169	;  //	An AttachmentSelection object.
	public final static int	olAutoFormatRule	=	147	;  //	An AutoFormatRule object.
	public final static int	olAutoFormatRules	=	148	;  //	An AutoFormatRules object.
	public final static int	olCalendarModule	=	159	;  //	A CalendarModule object.
	public final static int	olCalendarSharing	=	151	;  //	A CalendarSharing object.
	public final static int	olCategories	=	153	;  //	A Categories object.
	public final static int	olCategory	=	152	;  //	A Category object.
	public final static int	olCategoryRuleCondition	=	130	;  //	A CategoryRuleCondition object.
	public final static int	olClassBusinessCardView	=	168	;  //	A BusinessCardView object.
	public final static int	olClassCalendarView	=	139	;  //	A CalendarView object.
	public final static int	olClassCardView	=	138	;  //	A CardView object.
	public final static int	olClassIconView	=	137	;  //	An IconView object.
	public final static int	olClassNavigationPane	=	155	;  //	A NavigationPane object.
	public final static int	olClassTableView	=	136	;  //	A TableView object.
	public final static int	olClassTimeLineView	=	140	;  //	A TimelineView object.
	public final static int	olClassTimeZone	=	174	;  //	A TimeZone object.
	public final static int	olClassTimeZones	=	175	;  //	A TimeZones object.
	public final static int	olColumn	=	154	;  //	A Column object.
	public final static int	olColumnFormat	=	149	;  //	A ColumnFormat object.
	public final static int	olColumns	=	150	;  //	A Columns object.
	public final static int	olConflict	=	102	;  //	A Conflict object.
	public final static int	olConflicts	=	103	;  //	A Conflicts object.
	public final static int	olContact	=	40	;  //	A ContactItem object.
	public final static int	olContactsModule	=	160	;  //	A ContactsModule object.
	public final static int	olConversation	=	178	;  //	A Conversation object.
	public final static int	olConversationHeader	=	182	;  //	A ConversationHeader object.
	public final static int	olDistributionList	=	69	;  //	An ExchangeDistributionList object.
	public final static int	olDocument	=	41	;  //	A DocumentItem object.
	public final static int	olException	=	30	;  //	An Exception object.
	public final static int	olExceptions	=	29	;  //	An Exceptions object.
	public final static int	olExchangeDistributionList	=	111	;  //	An ExchangeDistributionList object.
	public final static int	olExchangeUser	=	110	;  //	An ExchangeUser object.
	public final static int	olExplorer	=	34	;  //	An Explorer object.
	public final static int	olExplorers	=	60	;  //	An Explorers object.
	public final static int	olFolder	=	2	;  //	A Folder object.
	public final static int	olFolders	=	15	;  //	A Folders object.
	public final static int	olFolderUserProperties	=	172	;  //	A UserDefinedProperties object.
	public final static int	olFolderUserProperty	=	171	;  //	A UserDefinedProperty object.
	public final static int	olFormDescription	=	37	;  //	A FormDescription object.
	public final static int	olFormNameRuleCondition	=	131	;  //	A FormNameRuleCondition object.
	public final static int	olFormRegion	=	129	;  //	A FormRegion object.
	public final static int	olFromRssFeedRuleCondition	=	173	;  //	A FromRssFeedRuleCondition object.
	public final static int	olFromRuleCondition	=	132	;  //	A ToOrFromRuleCondition object.
	public final static int	olImportanceRuleCondition	=	128	;  //	An ImportanceRuleCondition object.
	public final static int	olInspector	=	35	;  //	An Inspector object.
	public final static int	olInspectors	=	61	;  //	An Inspectors object.
	public final static int	olItemProperties	=	98	;  //	An ItemProperties object.
	public final static int	olItemProperty	=	99	;  //	An ItemProperty object.
	public final static int	olItems	=	16	;  //	An Items object.
	public final static int	olJournal	=	42	;  //	A JournalItem object.
	public final static int	olJournalModule	=	162	;  //	A JournalModule object.
	public final static int	olLink	=	75	;  //	A Link object.
	public final static int	olLinks	=	76	;  //	A Links object.
	public final static int	olMail	=	43	;  //	A MailItem object.
	public final static int	olMailModule	=	158	;  //	A MailModule object.
	public final static int	olMarkAsTaskRuleAction	=	124	;  //	A MarkAsTaskRuleAction object.
	public final static int	olMeetingCancellation	=	54	;  //	A MeetingItem object that is a meeting cancellation notice.
	public final static int	olMeetingForwardNotification	=	181	;  //	A MeetingItem object that is a notice about forwarding the meeting request.
	public final static int	olMeetingRequest	=	53	;  //	A MeetingItem object that is a meeting request.
	public final static int	olMeetingResponseNegative	=	55	;  //	A MeetingItem object that is a refusal of a meeting request.
	public final static int	olMeetingResponsePositive	=	56	;  //	A MeetingItem object that is an acceptance of a meeting request.
	public final static int	olMeetingResponseTentative	=	57	;  //	A MeetingItem object that is a tentative acceptance of a meeting request.
	public final static int	olMobile	=	176	;  //	A MobileItem object that is a text message item or a multimedia message item.
	public final static int	olMoveOrCopyRuleAction	=	118	;  //	A MoveOrCopyRuleAction object.
	public final static int	olNamespace	=	1	;  //	A NameSpace object.
	public final static int	olNavigationFolder	=	167	;  //	A NavigationFolder object.
	public final static int	olNavigationFolders	=	166	;  //	A NavigationFolders object.
	public final static int	olNavigationGroup	=	165	;  //	A NavigationGroup object.
	public final static int	olNavigationGroups	=	164	;  //	A NavigationGroups object.
	public final static int	olNavigationModule	=	157	;  //	A NavigationModule object.
	public final static int	olNavigationModules	=	156	;  //	A NavigationModules object.
	public final static int	olNewItemAlertRuleAction	=	125	;  //	A NewItemAlertRuleAction object.
	public final static int	olNote	=	44	;  //	A NoteItem object.
	public final static int	olNotesModule	=	163	;  //	A NotesModule object.
	public final static int	olOrderField	=	144	;  //	An OrderField object.
	public final static int	olOrderFields	=	145	;  //	An OrderFields object.
	public final static int	olOutlookBarGroup	=	66	;  //	An OutlookBarGroup object.
	public final static int	olOutlookBarGroups	=	65	;  //	An OutlookBarGroups object.
	public final static int	olOutlookBarPane	=	63	;  //	An OutlookBarPane object.
	public final static int	olOutlookBarShortcut	=	68	;  //	An OutlookBarShortcut object.
	public final static int	olOutlookBarShortcuts	=	67	;  //	An OutlookBarShortcuts object.
	public final static int	olOutlookBarStorage	=	64	;  //	An OutlookBarStorage object.
	public final static int	olOutspace	=	180	;  //	An AccountSelector object.
	public final static int	olPages	=	36	;  //	A Pages object.
	public final static int	olPanes	=	62	;  //	A Panes object.
	public final static int	olPlaySoundRuleAction	=	123	;  //	A PlaySoundRuleAction object.
	public final static int	olPost	=	45	;  //	A PostItem object.
	public final static int	olPropertyAccessor	=	112	;  //	A PropertyAccessor object.
	public final static int	olPropertyPages	=	71	;  //	A PropertyPages object.
	public final static int	olPropertyPageSite	=	70	;  //	A PropertyPageSite object.
	public final static int	olRecipient	=	4	;  //	A Recipient object.
	public final static int	olRecipients	=	17	;  //	A Recipients object.
	public final static int	olRecurrencePattern	=	28	;  //	A RecurrencePattern object.
	public final static int	olReminder	=	101	;  //	A Reminder object.
	public final static int	olReminders	=	100	;  //	A Reminders object.
	public final static int	olRemote	=	47	;  //	A RemoteItem object.
	public final static int	olReport	=	46	;  //	A ReportItem object.
	public final static int	olResults	=	78	;  //	A Results object.
	public final static int	olRow	=	121	;  //	A Row object.
	public final static int	olRule	=	115	;  //	A Rule object.
	public final static int	olRuleAction	=	117	;  //	A RuleAction object.
	public final static int	olRuleActions	=	116	;  //	A RuleActions object.
	public final static int	olRuleCondition	=	127	;  //	A RuleCondition object.
	public final static int	olRuleConditions	=	126	;  //	A RuleConditions object.
	public final static int	olRules	=	114	;  //	A Rules object.
	public final static int	olSearch	=	77	;  //	A Search object.
	public final static int	olSelection	=	74	;  //	A Selection object.
	public final static int	olSelectNamesDialog	=	109	;  //	A SelectNamesDialog object.
	public final static int	olSenderInAddressListRuleCondition	=	133	;  //	A SenderInAddressListRuleCondition object.
	public final static int	olSendRuleAction	=	119	;  //	A SendRuleAction object.
	public final static int	olSharing	=	104	;  //	A SharingItem object.
	public final static int	olSimpleItems	=	179	;  //	A SimpleItems object.
	public final static int	olSolutionsModule	=	177	;  //	A SolutionsModule object.
	public final static int	olStorageItem	=	113	;  //	A StorageItem object.
	public final static int	olStore	=	107	;  //	A Store object.
	public final static int	olStores	=	108	;  //	A Stores object.
	public final static int	olSyncObject	=	72	;  //	A SyncObject object.
	public final static int	olSyncObjects	=	73	;  //	A SyncObjects object.
	public final static int	olTable	=	120	;  //	A Table object.
	public final static int	olTask	=	48	;  //	A TaskItem object.
	public final static int	olTaskRequest	=	49	;  //	A TaskRequestItem object.
	public final static int	olTaskRequestAccept	=	51	;  //	A TaskRequestAcceptItem object.
	public final static int	olTaskRequestDecline	=	52	;  //	A TaskRequestDeclineItem object.
	public final static int	olTaskRequestUpdate	=	50	;  //	A TaskRequestUpdateItem object.
	public final static int	olTasksModule	=	161	;  //	A TasksModule object.
	public final static int	olTextRuleCondition	=	134	;  //	A TextRuleCondition object.
	public final static int	olUserDefinedProperties	=	172	;  //	A UserDefinedProperties object.
	public final static int	olUserDefinedProperty	=	171	;  //	A UserDefinedProperty object.
	public final static int	olUserProperties	=	38	;  //	A UserProperties object.
	public final static int	olUserProperty	=	39	;  //	A UserProperty object.
	public final static int	olView	=	80	;  //	A View object.
	public final static int	olViewField	=	142	;  //	A ViewField object.
	public final static int	olViewFields	=	141	;  //	A ViewFields object.
	public final static int	olViewFont	=	146	;  //	A ViewFont object.
	public final static int	olViews	=	79	;  //	A Views object.

}
